# Generated by Django 4.2.4 on 2023-08-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.TextField(choices=[('stable', 'stable'), ('beta', 'beta')])),
                ('current_version', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.URLField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_email', models.TextField()),
                ('user_phone', models.TextField()),
                ('company_name', models.TextField()),
                ('company_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.URLField()),
                ('description', models.TextField()),
                ('type', models.TextField(choices=[('PFE', 'PFE'), ('Init', 'Init')])),
                ('date', models.DateField()),
                ('hr_email', models.TextField()),
                ('hr_phone', models.TextField()),
                ('apply_link', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='OfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('company_name', models.TextField()),
                ('user_company_role', models.TextField()),
                ('user_email', models.TextField()),
                ('user_phone', models.TextField()),
                ('offer_title', models.TextField()),
                ('offer_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offer')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.technology')),
            ],
        ),
        migrations.CreateModel(
            name='OfferReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_company', models.TextField()),
                ('user_email', models.TextField()),
                ('user_phone', models.TextField()),
                ('report_details', models.TextField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.location')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.industry')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offer')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.technology')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_company', models.TextField()),
                ('user_email', models.TextField()),
                ('user_phone', models.TextField()),
                ('report_details', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.location')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.industry')),
            ],
        ),
    ]
