# Generated by Django 4.2.4 on 2023-08-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='type',
            new_name='Type',
        ),
    ]
